-- SELECT STATEMENTS
SELECT * FROM money;

-- INSERT STATEMENTS

--REMOVE AND CREATE TABLE
CREATE TABLE money (name TEXT NOT NULL, amount INT NOT NULL,frequency TEXT NOT NULL, type TEXT NOT NULL);
drop table money;